[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turjuman-book-translator"
version = "0.0.1"
description = "Book translator based on Turjuman LangGraph"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
# look in the repo root (“.”) and include turjuman + subpackages
where = ["."]
include = ["turjuman*"]
